In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
import warnings
warnings.filterwarnings('ignore')


# Linear reg

In [2]:
dataset=pd.read_csv("emp_sal (1).csv")

In [3]:
dataset

,Position,Level,Salary
0,Jr Software Engineer,1,45000
1,Sr Software Engineer,2,50000
2,Team Lead,3,60000
3,Manager,4,80000
4,Sr manager,5,110000
5,Region Manager,6,150000
6,AVP,7,200000
7,VP,8,300000
8,CTO,9,500000
9,CEO,10,1000000


In [4]:
x=dataset[['Level']].values
y=dataset[['Salary']].values

In [5]:
lin_reg=LinearRegression()
lin_reg.fit(x,y)
lin_pred=lin_reg.predict([[6.5]])

lin_pred

array([[330378.78787879]])

# polynomia reg


In [6]:
poly_reg=PolynomialFeatures(degree=5)
x_poly=poly_reg.fit_transform(x)

lin_reg_2=LinearRegression()
lin_reg_2.fit(x_poly,y)

lin_poly_pred=lin_reg_2.predict(poly_reg.transform([[6.5]]))
lin_poly_pred

array([[174878.07765172]])

# SVR

In [7]:
svr_reg=SVR(kernel='poly',degree=4,C=10.0,gamma='auto')
svr_reg.fit(x,y)
svr_pred=svr_reg.predict([[6.5]])
svr_pred

array([175705.60452113])

# knn

In [8]:
knn_reg=KNeighborsRegressor(weights='distance',p=1)
knn_reg.fit(x,y)
knn_pred=knn_reg.predict([[6.5]])
knn_pred

array([[175348.8372093]])

# Desicion tree


In [11]:
dt_reg=DecisionTreeRegressor(criterion='poisson',max_depth=5,min_samples_split=3)
dt_reg.fit(x,y)
dt_pred=dt_reg.predict([[6.5]])
dt_pred

array([175000.])

# random forest

In [15]:
rf_reg=RandomForestRegressor(criterion='poisson',random_state=0,n_estimators=20,min_samples_split=3)
rf_reg.fit(x,y)
rf_pred=rf_reg.predict([[6.5]])
rf_pred

array([177208.33333333])

In [ ]:
# poly - 174.8k
# random forest -177.2k
# decision tree=175k
# knn =175.3k
# svr = 175.7k