In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [31]:
dataset=pd.read_csv(r"C:\Users\beher\OneDrive\Desktop\ML\classification\logit classification.csv")

In [32]:
dataset.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


In [33]:
x=dataset.drop(['User ID','Gender','Purchased'],axis=1)
y=dataset['Purchased']

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Bernouli

In [21]:
bn=BernoulliNB()
bn.fit(x_train,y_train)
y_pred=bn.predict(x_test)
ac=accuracy_score(y_test,y_pred)
print(ac)

0.825


In [23]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.83      0.95      0.89        58
           1       0.79      0.50      0.61        22

    accuracy                           0.82        80
   macro avg       0.81      0.72      0.75        80
weighted avg       0.82      0.82      0.81        80



In [24]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[55  3]
 [11 11]]


# Multinumial

In [35]:
nr=MinMaxScaler()
x_train=nr.fit_transform(x_train)
x_test=nr.transform(x_test)

In [36]:
mb=MultinomialNB()
mb.fit(x_train,y_train)
y_pred=mb.predict(x_test)

In [39]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
y_train.value_counts()

[[58  0]
 [22  0]]


Purchased
0    199
1    121
Name: count, dtype: int64

In [40]:
import warnings
warnings.filterwarnings('ignore')
cr=classification_report(y_test,y_pred)
print(cr)


              precision    recall  f1-score   support

           0       0.72      1.00      0.84        58
           1       0.00      0.00      0.00        22

    accuracy                           0.72        80
   macro avg       0.36      0.50      0.42        80
weighted avg       0.53      0.72      0.61        80



In [41]:
ac=accuracy_score(y_test,y_pred)

In [42]:
ac

0.725

# Gauusian

In [12]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [13]:
gb=GaussianNB()
gb.fit(x_train,y_train)
y_pred=gb.predict(x_test)

In [14]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.93      0.95      0.94        58
           1       0.86      0.82      0.84        22

    accuracy                           0.91        80
   macro avg       0.89      0.88      0.89        80
weighted avg       0.91      0.91      0.91        80



In [15]:
ac=accuracy_score(y_test,y_pred)
ac

0.9125

In [16]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[55  3]
 [ 4 18]]
